import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import '@/styles/globals.scss'
import fetcher from '@/services/fetcher'
import { IUser } from '@/types/user'
import { ENV_VARS } from '@/constants/env-vars'
import { UserProvider } from '@/store/provider/UserProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function fetchMockUserData() {
  const result = await fetcher<IUser>(`${ENV_VARS.baseUrl}/users/1`)
  return result
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const user = await fetchMockUserData()

  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider initialUserData={user}>
          <Header />
          <div className="page-container">
            <div className="page-content">{children}</div>
          </div>
          <Footer />
        </UserProvider>
      </body>
    </html>
  )
}
